services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MARIADB_DATABASE=wedding #not a secret
      - MARIADB_USER=user #not a secret
      - MARIADB_PASSWORD_FILE=/run/secrets/password_db
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/password_db_root
    secrets:
       - password_db_root
       - password_db
    volumes:
      - ./mariadb/data:/config
      - ./mariadb/init-db:/docker-entrypoint-initdb.d:ro
      - ./mariadb/my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - 3306:3306
    restart: unless-stopped
  nginx:
    image: andrewnk/alpine-nginx-modsec
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
    restart: unless-stopped

volumes:
  app:

secrets:
   password_db:
     file: password_db.txt
   password_db_root:
     file: password_db_root.txt