services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        GID: ${GID}
        UID: ${UID}
    environment:
      - CONTAINER=true
      - GID=${GID}
      - UID=${UID}
      - CATAPUSH_MOBILE_APP_ID=${CATAPUSH_MOBILE_APP_ID}
      - CATAPUSH_IDENTIFIER=${CATAPUSH_IDENTIFIER}
      - CATAPUSH_API_KEY=${CATAPUSH_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHATID=${CHATID}
    tty: true
    secrets:
       - password_db
       - cookie_passphrase
    volumes:
      - ./logs/backend:/tmp/logs
      - ./backend-io/:/app/io/
    ports:
      - "8080:8080"
    networks:
      - stack
    depends_on:
      - mariadb
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    volumes:
      - frontend:/app/build
  mariadb:
    build:
      context: .
      dockerfile: mariadb.dockerfile
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MARIADB_DATABASE=wedding #not a secret
      - MARIADB_USER=user #not a secret
      - MARIADB_PASSWORD_FILE=/run/secrets/password_db
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/password_db_root
      - MARIADB_AUTO_UPGRADE=1
    secrets:
       - password_db_root
       - password_db
    volumes:
      - ./mariadb/data:/config
      - ./mariadb/init-db:/docker-entrypoint-initdb.d:ro
      - ./mariadb/my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - 3306:3306
    networks:
      - stack
    restart: unless-stopped
  nginx:
    image: andrewnk/alpine-nginx-modsec
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - mariadb
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/modsecurity/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
      - ./nginx/modsecurity/crs-setup.conf:/usr/local/owasp-modsecurity-crs/crs-setup.conf
      - ./nginx/errors/403.html:/usr/share/nginx/errors/403.html
      - ./nginx/errors/404.html:/usr/share/nginx/errors/404.html
      - ./nginx/errors/50x.html:/usr/share/nginx/errors/50x.html
      - ./nginx/errors/5xx.html:/usr/share/nginx/errors/5xx.html
      - ./frontend/public/images:/usr/share/nginx/images
      - ./frontend/public/icon.png:/usr/share/nginx/images/icon.png
      - ./logs/nginx/:/var/log/nginx/
      - ./logs/nginx/var/log/:/var/log/
      - frontend:/app/frontend/build
    networks:
      - stack
    restart: unless-stopped
  adminer:
    image: adminer
    ports:
      - 9000:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb
    networks:
      - stack
networks:
  stack:
    driver: bridge

volumes:
  logs:
  frontend:

secrets:
  password_db:
    file: password_db.txt
  password_db_root:
    file: password_db_root.txt
  cookie_passphrase:
    file: cookie-passphrase.txt